import json

# Read the extracted keys
with open('extracted_keys.json', 'r') as f:
    keys = json.load(f)

# Existing FR and ID
try:
    with open('lang/fr.json', 'r') as f:
        fr_existing = json.load(f)
except:
    fr_existing = {}

try:
    with open('lang/id.json', 'r') as f:
        id_existing = json.load(f)
except:
    id_existing = {}

# Translations dictionary (manual additions for missing ones)
fr_new = {
    "Global (All Funds)": "Global (Tous les Fonds)",
    "Direct Post": "Écriture Directe",
    "Uncategorized": "Non catégorisé",
    "General": "Général",
    "Transaction created successfully and is awaiting validation.": "Transaction créée avec succès et en attente de validation.",
    "Transaction approved successfully.": "Transaction approuvée avec succès.",
    "Transaction rejected.": "Transaction rejetée.",
    "Fund created successfully.": "Fonds créé avec succès.",
    "Fund updated successfully.": "Fonds mis à jour avec succès.",
    "Cannot delete a fund that contains transactions.": "Impossible de supprimer un fonds contenant des transactions.",
    "Fund deleted successfully.": "Fonds supprimé avec succès.",
    "Member created successfully.": "Membre créé avec succès.",
    "Member updated successfully.": "Membre mis à jour avec succès.",
    "Cannot delete member because they have registered contributions. Set them to exempted instead.": "Impossible de supprimer le membre car il a des cotisations enregistrées. Définissez-le comme exempté à la place.",
    "Member deleted successfully.": "Membre supprimé avec succès.",
    "Cannot assign a sub-category as a parent.": "Impossible d'assigner une sous-catégorie comme parent.",
    "The type field is required for main categories.": "Le champ type est requis pour les catégories principales.",
    "Category created successfully.": "Catégorie créée avec succès.",
    "Category cannot be its own parent.": "La catégorie ne peut pas être son propre parent.",
    "Cannot assign a parent to a category that already has sub-categories.": "Impossible d'assigner un parent à une catégorie ayant déjà des sous-catégories.",
    "Category updated successfully.": "Catégorie mise à jour avec succès.",
    "Cannot delete a category that has sub-categories. Please delete them first.": "Impossible de supprimer une catégorie ayant des sous-catégories. Veuillez d'abord les supprimer.",
    "Cannot delete a category that has associated transactions.": "Impossible de supprimer une catégorie ayant des transactions associées.",
    "Category deleted successfully.": "Catégorie supprimée avec succès.",
    "User created successfully.": "Utilisateur créé avec succès.",
    "User updated successfully.": "Utilisateur mis à jour avec succès.",
    "Cash Flow": "Flux de Trésorerie",
    "Cash Flow Statement": "État des Flux de Trésorerie",
    "Monthly summary of incomes and expenses": "Résumé mensuel des revenus et dépenses",
    "Date": "Date",
    "Description": "Description",
    "Amount": "Montant",
    "Income": "Revenu",
    "Last Month\\'s Balance": "Solde du mois précédent",
    "No income recorded": "Aucun revenu enregistré",
    "Expense": "Dépense",
    "No expenses recorded": "Aucune dépense enregistrée",
    "Balance": "Solde",
    "Back to Dashboard": "Retour au tableau de bord",
    "Add New Transaction": "Ajouter une transaction",
    "Transaction Type": "Type de transaction",
    "Select Type": "Sélectionner le type",
    "Amount (Rp)": "Montant (Rp)",
    "Example: 150000": "Exemple : 150000",
    "Category (Detail Account)": "Catégorie (Compte détaillé)",
    "Select Category": "Sélectionner une catégorie",
    "Fund": "Fonds",
    "Select Fund": "Sélectionner un fonds",
    "Transaction details...": "Détails de la transaction...",
    "Transaction Proof (Optional, Max 2MB, JPG/PNG/PDF)": "Preuve de transaction (Optionnel, Max 2Mo, JPG/PNG/PDF)",
    "Save Transaction (Pending)": "Enregistrer la transaction (En attente)",
    "Financial Journal": "Journal Financier",
    "Complete history of village financial activities": "Historique complet des activités financières du village",
    "New Entry": "Nouvelle Entrée",
    "Search transactions...": "Rechercher des transactions...",
    "Filter": "Filtrer",
    "Running Balance": "Solde Courant",
    "Status": "Statut",
    "System": "Système",
    "Unknown Fund": "Fonds inconnu",
    "Validated": "Validé",
    "Pending": "En attente",
    "Rejected": "Rejeté",
    "No transactions found.": "Aucune transaction trouvée.",
    "Start by creating a new entry.": "Commencez par créer une nouvelle entrée.",
    "Pending Transactions": "Transactions en attente",
    "Requires your approval": "Nécessite votre approbation",
    "No pending transactions at the moment.": "Aucune transaction en attente pour le moment.",
    "Creator": "Créateur",
    "Category & Detail": "Catégorie & Détail",
    "Actions": "Actions",
    "Unknown": "Inconnu",
    "Approve": "Approuver",
    "Reject": "Rejeter",
    "LPJ Preview": "Aperçu du LPJ",
    "Laporan Pertanggungjawaban (LPJ)": "Laporan Pertanggungjawaban (LPJ)",
    "Period": "Période",
    "Scope": "Périmètre",
    "Share (Public)": "Partager (Public)",
    "Copied!": "Copié !",
    "Starting Balance": "Solde initial",
    "Incomes": "Revenus",
    "No income recorded in this period.": "Aucun revenu enregistré pour cette période.",
    "Total Incomes": "Total des revenus",
    "Expenses": "Dépenses",
    "No expenses recorded in this period.": "Aucune dépense enregistrée pour cette période.",
    "Total Expenses": "Total des dépenses",
    "Ending Balance": "Solde final",
    "LPJ Reports": "Rapports LPJ",
    "Financial Reports (LPJ)": "Rapports Financiers (LPJ)",
    "Generate official Laporan Pertanggungjawaban for the village assembly.": "Générer le Laporan Pertanggungjawaban officiel pour l'assemblée du village.",
    "Start Date": "Date de début",
    "End Date": "Date de fin",
    "Select a specific fund for targeted auditing, or leave blank for the consolidated village report.": "Sélectionnez un fonds spécifique pour un audit ciblé, ou laissez vide pour le rapport consolidé du village.",
    "Generate Preview": "Générer l'aperçu",
    "Financial Report": "Rapport Financier",
    "Income Distribution": "Répartition des revenus",
    "No income data": "Aucune donnée de revenu",
    "Expense Distribution": "Répartition des dépenses",
    "No expense data": "Aucune donnée de dépense",
    "Income Details": "Détails des revenus",
    "No data available": "Aucune donnée disponible",
    "Expense Details": "Détails des dépenses",
    "Edit User": "Modifier l'utilisateur",
    "Back to Users List": "Retour à la liste des utilisateurs",
    "Update user data, role, or active status.": "Mettre à jour les données de l'utilisateur, son rôle ou son statut.",
    "ACTIVE": "ACTIF",
    "INACTIVE": "INACTIF",
    "Username": "Nom d'utilisateur",
    "Email Address": "Adresse email",
    "Role": "Rôle",
    "Member": "Membre",
    "Treasurer": "Trésorier",
    "Kelian": "Kelian",
    "Active Account (Can Login)": "Compte Actif (Peut se connecter)",
    "Uncheck to deactivate this account. The user will not be able to log in.": "Décochez pour désactiver ce compte. L'utilisateur ne pourra pas se connecter.",
    "Change Password (Optional)": "Changer le mot de passe (Optionnel)",
    "New Password": "Nouveau mot de passe",
    "Leave blank if not changing": "Laisser vide si inchangé",
    "Confirm New Password": "Confirmer le nouveau mot de passe",
    "Repeat new password": "Répéter le nouveau mot de passe",
    "Cancel": "Annuler",
    "Update User": "Mettre à jour l'utilisateur",
    "Add User": "Ajouter un utilisateur",
    "User Form": "Formulaire utilisateur",
    "Fill in the data below to create a new account.": "Remplissez les données ci-dessous pour créer un nouveau compte.",
    "Password": "Mot de passe",
    "Confirm Password": "Confirmer le mot de passe",
    "Save User": "Enregistrer l'utilisateur",
    "User Management": "Gestion des utilisateurs",
    "Users List": "Liste des utilisateurs",
    "Email": "Email",
    "Active": "Actif",
    "Inactive": "Inactif",
    "Edit": "Modifier",
    "Edit Category": "Modifier la Catégorie",
    "Modify the details of your account category.": "Modifiez les détails de la catégorie de compte.",
    "Category Name": "Nom de la catégorie",
    "Parent Category (Optional)": "Catégorie parente (Optionnel)",
    "Main Category (No Parent)": "Catégorie principale (Aucun parent)",
    "Cannot assign a parent because this category has sub-categories.": "Impossible d'assigner un parent car cette catégorie a des sous-catégories.",
    "Select a parent category to make this a sub-category.": "Sélectionnez une catégorie parente pour en faire une sous-catégorie.",
    "Account Type": "Type de compte",
    "Sub-categories will automatically inherit their parent\\'s type.": "Les sous-catégories hériteront automatiquement du type de leur parent.",
    "Update Category": "Mettre à jour la catégorie",
    "Create Category": "Créer une catégorie",
    "Create New Category": "Créer une Nouvelle Catégorie",
    "Add a new account to your Chart of Accounts.": "Ajouter un nouveau compte à votre plan comptable.",
    "Select a parent category to create a sub-category.": "Sélectionnez une catégorie parente pour créer une sous-catégorie.",
    "Save Category": "Enregistrer la catégorie",
    "Chart of Accounts": "Plan Comptable",
    "Organize your income and expense categories (MYOB Accounting Logic).": "Organisez vos catégories de revenus et dépenses (Logique comptable MYOB).",
    "New Category": "Nouvelle Catégorie",
    "Income Accounts": "Comptes de Revenus",
    "No income categories configured.": "Aucune catégorie de revenus configurée.",
    "Recurring": "Récurrent",
    "Are you sure?": "Êtes-vous sûr(e) ?",
    "Delete": "Supprimer",
    "Expense Accounts": "Comptes de Dépenses",
    "No expense categories configured.": "Aucune catégorie de dépenses configurée.",
    "Edit Member": "Modifier le membre",
    "Back to List": "Retour à la liste",
    "Member Name": "Nom du membre",
    "Community Group": "Groupe Communautaire",
    "Select a Group": "Sélectionner un groupe",
    "Exempted": "Exempté",
    "Update Member": "Mettre à jour le membre",
    "Add Member": "Ajouter un membre",
    "Save Member": "Enregistrer le membre",
    "Members": "Membres",
    "Members Management": "Gestion des Membres",
    "Name": "Nom",
    "Group": "Groupe",
    "N/A": "N/D",
    "Are you sure you want to delete this member?": "Êtes-vous sûr de vouloir supprimer ce membre ?",
    "No members found.": "Aucun membre trouvé.",
    "Contributions Tracking": "Suivi des Cotisations",
    "Manage monthly payments for each member. Changes are saved instantly.": "Gérez les paiements mensuels de chaque membre. Les modifications sont enregistrées instantanément.",
    "Period (YYYY-MM)": "Période (AAAA-MM)",
    "Load Grid": "Charger la grille",
    "Payment Status": "Statut du paiement",
    "Paid": "Payé",
    "No members found. Please add members first.": "Aucun membre trouvé. Veuillez d'abord ajouter des membres.",
    "Failed to update status. Please try again.": "Échec de la mise à jour du statut. Veuillez réessayer.",
    "Network error. Could not update status.": "Erreur réseau. Impossible de mettre à jour le statut.",
    "Dashboard Analytics": "Analyses du Tableau de Bord",
    "Transactions awaiting validation": "Transactions en attente de validation",
    "You have": "Vous avez",
    "transactions to review in the queue.": "transactions à examiner dans la file d'attente.",
    "Review Queue": "File d'attente d'examen",
    "Total Fund Balance": "Solde Total du Fonds",
    "Incomes This Month": "Revenus de ce mois",
    "Expenses This Month": "Dépenses de ce mois",
    "This Month: Income vs Expense": "Ce Mois : Revenus vs Dépenses",
    "No transactions this month.": "Aucune transaction ce mois-ci.",
    "6-Month Cash Flow Trend": "Tendance des flux de trésorerie sur 6 mois",
    "6-Month Financial Projection": "Projection financière sur 6 mois",
    "Calculated MRR (Monthly Recurring Revenue):": "MRR calculé (Revenu Mensuel Récurrent) :",
    "Projections are calculated dynamically using the 6-month average of categories marked as \"Recurring\", minus any planned activity budgets.": "Les projections sont calculées dynamiquement à l'aide de la moyenne sur 6 mois des catégories marquées comme \"Récurrentes\", moins les budgets d'activités prévus.",
    "Latest Transactions": "Dernières transactions",
    "View All": "Voir Tout",
    "No recent transactions found.": "Aucune transaction récente trouvée.",
    "Upcoming Activities": "Activités à venir",
    "No upcoming events planned.": "Aucun événement prévu.",
    "Budget": "Budget",
    "Projected Balance": "Solde projeté",
    "Edit Fund": "Modifier le fonds",
    "Back to Funds": "Retour aux fonds",
    "Update the details of this community fund. The balance cannot be changed manually.": "Mettez à jour les détails de ce fonds communautaire. Le solde ne peut pas être modifié manuellement.",
    "Current Balance": "Solde actuel",
    "Fund Name": "Nom du fonds",
    "Associated Group (Optional)": "Groupe associé (Optionnel)",
    "No Group / General Fund": "Aucun groupe / Fonds général",
    "Associated Activity (Optional)": "Activité associée (Optionnel)",
    "No Specific Activity": "Aucune activité spécifique",
    "Update Fund": "Mettre à jour le fonds",
    "Create Fund": "Créer un fonds",
    "Create New Fund": "Créer un nouveau fonds",
    "Create a new community fund. The initial balance will always be set to Rp 0.": "Créez un nouveau fonds communautaire. Le solde initial sera toujours défini sur 0 Rp.",
    "e.g., Kas Umum, Kas Pembangunan": "ex: Caisse Générale, Caisse de Développement",
    "Describe the purpose of this fund (optional)": "Décrivez l'objectif de ce fonds (optionnel)",
    "Save Fund": "Enregistrer le fonds",
    "Funds Management": "Gestion des Fonds",
    "Manage community funds and view their current balances.": "Gérez les fonds de la communauté et consultez leurs soldes actuels.",
    "New Fund": "Nouveau Fonds",
    "Are you sure you want to delete this fund? This action cannot be undone.": "Êtes-vous sûr de vouloir supprimer ce fonds ? Cette action est irréversible.",
    "No Funds Found": "Aucun fonds trouvé",
    "You have not created any funds yet. Create your first fund to start tracking financial transactions.": "Vous n'avez pas encore créé de fonds. Créez votre premier fonds pour commencer à suivre les transactions financières.",
    "Create Your First Fund": "Créez votre premier fonds",
    "Dashboard": "Tableau de Bord",
    "New Transaction": "Nouvelle Transaction",
    "Reports (LPJ)": "Rapports (LPJ)",
    "Logout": "Déconnexion",
    "Back": "Retour",
    "Public Transparency": "Transparence Publique",
    "Generated automatically for public transparency.": "Généré automatiquement pour la transparence publique.",
    "pagination.previous": "Précédent",
    "pagination.next": "Suivant",
    "Pagination Navigation": "Navigation de pagination",
    "Showing": "Affichage de",
    "to": "à",
    "of": "sur",
    "results": "résultats",
    "Service Unavailable": "Service Indisponible",
    "Unauthorized": "Non autorisé",
    "Too Many Requests": "Trop de requêtes",
    "Forbidden": "Interdit",
    "Payment Required": "Paiement requis",
    "Page Expired": "Page expirée",
    "Not Found": "Introuvable",
    "Server Error": "Erreur serveur",
    "All rights reserved.": "Tous droits réservés.",
    "transactions to review.": "transactions à examiner.",
    "Latest 5 Transactions": "5 dernières transactions",
    "Upcoming Events & Activities": "Événements & Activités à venir",
    "Planning": "Planification",
    "Status:": "Statut :",
    "Until": "Jusqu'à"
}

id_new = {
    "Global (All Funds)": "Global (Semua Kas)",
    "Direct Post": "Pencatatan Langsung",
    "Uncategorized": "Tanpa Kategori",
    "General": "Umum",
    "Transaction created successfully and is awaiting validation.": "Transaksi berhasil dibuat dan menunggu validasi.",
    "Transaction approved successfully.": "Transaksi berhasil disetujui.",
    "Transaction rejected.": "Transaksi ditolak.",
    "Fund created successfully.": "Kas berhasil dibuat.",
    "Fund updated successfully.": "Kas berhasil diperbarui.",
    "Cannot delete a fund that contains transactions.": "Tidak dapat menghapus kas yang berisi transaksi.",
    "Fund deleted successfully.": "Kas berhasil dihapus.",
    "Member created successfully.": "Anggota berhasil dibuat.",
    "Member updated successfully.": "Anggota berhasil diperbarui.",
    "Cannot delete member because they have registered contributions. Set them to exempted instead.": "Tidak dapat menghapus anggota karena mereka memiliki kontribusi yang terdaftar. Atur mereka sebagai dikecualikan (exempted).",
    "Member deleted successfully.": "Anggota berhasil dihapus.",
    "Cannot assign a sub-category as a parent.": "Tidak dapat menetapkan sub-kategori sebagai induk.",
    "The type field is required for main categories.": "Bidang tipe diperlukan untuk kategori utama.",
    "Category created successfully.": "Kategori berhasil dibuat.",
    "Category cannot be its own parent.": "Kategori tidak bisa menjadi induknya sendiri.",
    "Cannot assign a parent to a category that already has sub-categories.": "Tidak dapat menetapkan induk ke kategori yang sudah memiliki sub-kategori.",
    "Category updated successfully.": "Kategori berhasil diperbarui.",
    "Cannot delete a category that has sub-categories. Please delete them first.": "Tidak dapat menghapus kategori yang memiliki sub-kategori. Harap hapus terlebih dahulu.",
    "Cannot delete a category that has associated transactions.": "Tidak dapat menghapus kategori yang memiliki transaksi terkait.",
    "Category deleted successfully.": "Kategori berhasil dihapus.",
    "User created successfully.": "Pengguna berhasil dibuat.",
    "User updated successfully.": "Pengguna berhasil diperbarui.",
    "Cash Flow": "Arus Kas",
    "Cash Flow Statement": "Laporan Arus Kas",
    "Monthly summary of incomes and expenses": "Ringkasan bulanan pemasukan dan pengeluaran",
    "Date": "Tanggal",
    "Description": "Deskripsi",
    "Amount": "Jumlah",
    "Income": "Pemasukan",
    "Last Month\\'s Balance": "Saldo Bulan Lalu",
    "No income recorded": "Tidak ada pemasukan tercatat",
    "Expense": "Pengeluaran",
    "No expenses recorded": "Tidak ada pengeluaran tercatat",
    "Balance": "Saldo",
    "Back to Dashboard": "Kembali ke Dashboard",
    "Add New Transaction": "Tambah Transaksi Baru",
    "Transaction Type": "Tipe Transaksi",
    "Select Type": "Pilih Tipe",
    "Amount (Rp)": "Jumlah (Rp)",
    "Example: 150000": "Contoh: 150000",
    "Category (Detail Account)": "Kategori (Detail Akun)",
    "Select Category": "Pilih Kategori",
    "Fund": "Kas",
    "Select Fund": "Pilih Kas",
    "Transaction details...": "Detail transaksi...",
    "Transaction Proof (Optional, Max 2MB, JPG/PNG/PDF)": "Bukti Transaksi (Opsional, Max 2MB, JPG/PNG/PDF)",
    "Save Transaction (Pending)": "Simpan Transaksi (Pending)",
    "Financial Journal": "Jurnal Keuangan",
    "Complete history of village financial activities": "Riwayat lengkap aktivitas keuangan desa",
    "New Entry": "Entri Baru",
    "Search transactions...": "Cari transaksi...",
    "Filter": "Filter",
    "Running Balance": "Saldo Berjalan",
    "Status": "Status",
    "System": "Sistem",
    "Unknown Fund": "Kas Tidak Diketahui",
    "Validated": "Divalidasi",
    "Pending": "Tertunda",
    "Rejected": "Ditolak",
    "No transactions found.": "Tidak ada transaksi ditemukan.",
    "Start by creating a new entry.": "Mulai dengan membuat entri baru.",
    "Pending Transactions": "Transaksi Tertunda",
    "Requires your approval": "Membutuhkan persetujuan Anda",
    "No pending transactions at the moment.": "Tidak ada transaksi tertunda saat ini.",
    "Creator": "Pembuat",
    "Category & Detail": "Kategori & Detail",
    "Actions": "Aksi",
    "Unknown": "Tidak Diketahui",
    "Approve": "Setujui",
    "Reject": "Tolak",
    "LPJ Preview": "Pratinjau LPJ",
    "Laporan Pertanggungjawaban (LPJ)": "Laporan Pertanggungjawaban (LPJ)",
    "Period": "Periode",
    "Scope": "Cakupan",
    "Share (Public)": "Bagikan (Publik)",
    "Copied!": "Tersalin!",
    "Starting Balance": "Saldo Awal",
    "Incomes": "Pemasukan",
    "No income recorded in this period.": "Tidak ada pemasukan tercatat pada periode ini.",
    "Total Incomes": "Total Pemasukan",
    "Expenses": "Pengeluaran",
    "No expenses recorded in this period.": "Tidak ada pengeluaran tercatat pada periode ini.",
    "Total Expenses": "Total Pengeluaran",
    "Ending Balance": "Saldo Akhir",
    "LPJ Reports": "Laporan LPJ",
    "Financial Reports (LPJ)": "Laporan Keuangan (LPJ)",
    "Generate official Laporan Pertanggungjawaban for the village assembly.": "Buat Laporan Pertanggungjawaban resmi untuk rapat desa.",
    "Start Date": "Tanggal Mulai",
    "End Date": "Tanggal Akhir",
    "Select a specific fund for targeted auditing, or leave blank for the consolidated village report.": "Pilih kas spesifik untuk audit terarah, atau biarkan kosong untuk laporan desa terkonsolidasi.",
    "Generate Preview": "Buat Pratinjau",
    "Financial Report": "Laporan Keuangan",
    "Income Distribution": "Distribusi Pemasukan",
    "No income data": "Tidak ada data pemasukan",
    "Expense Distribution": "Distribusi Pengeluaran",
    "No expense data": "Tidak ada data pengeluaran",
    "Income Details": "Detail Pemasukan",
    "No data available": "Tidak ada data tersedia",
    "Expense Details": "Detail Pengeluaran",
    "Edit User": "Edit Pengguna",
    "Back to Users List": "Kembali ke Daftar Pengguna",
    "Update user data, role, or active status.": "Perbarui data pengguna, peran, atau status aktif.",
    "ACTIVE": "AKTIF",
    "INACTIVE": "NONAKTIF",
    "Username": "Nama Pengguna",
    "Email Address": "Alamat Email",
    "Role": "Peran",
    "Member": "Anggota",
    "Treasurer": "Bendahara",
    "Kelian": "Kelian",
    "Active Account (Can Login)": "Akun Aktif (Bisa Login)",
    "Uncheck to deactivate this account. The user will not be able to log in.": "Hapus centang untuk menonaktifkan akun ini. Pengguna tidak akan bisa login.",
    "Change Password (Optional)": "Ubah Kata Sandi (Opsional)",
    "New Password": "Kata Sandi Baru",
    "Leave blank if not changing": "Biarkan kosong jika tidak mengubah",
    "Confirm New Password": "Konfirmasi Kata Sandi Baru",
    "Repeat new password": "Ulangi kata sandi baru",
    "Cancel": "Batal",
    "Update User": "Perbarui Pengguna",
    "Add User": "Tambah Pengguna",
    "User Form": "Formulir Pengguna",
    "Fill in the data below to create a new account.": "Isi data di bawah ini untuk membuat akun baru.",
    "Password": "Kata Sandi",
    "Confirm Password": "Konfirmasi Kata Sandi",
    "Save User": "Simpan Pengguna",
    "User Management": "Manajemen Pengguna",
    "Users List": "Daftar Pengguna",
    "Email": "Email",
    "Active": "Aktif",
    "Inactive": "Nonaktif",
    "Edit": "Edit",
    "Edit Category": "Edit Kategori",
    "Modify the details of your account category.": "Ubah detail kategori akun Anda.",
    "Category Name": "Nama Kategori",
    "Parent Category (Optional)": "Kategori Induk (Opsional)",
    "Main Category (No Parent)": "Kategori Utama (Tanpa Induk)",
    "Cannot assign a parent because this category has sub-categories.": "Tidak dapat menetapkan induk karena kategori ini memiliki sub-kategori.",
    "Select a parent category to make this a sub-category.": "Pilih kategori induk untuk menjadikannya sub-kategori.",
    "Account Type": "Tipe Akun",
    "Sub-categories will automatically inherit their parent\\'s type.": "Sub-kategori akan secara otomatis mewarisi tipe induknya.",
    "Update Category": "Perbarui Kategori",
    "Create Category": "Buat Kategori",
    "Create New Category": "Buat Kategori Baru",
    "Add a new account to your Chart of Accounts.": "Tambahkan akun baru ke Bagan Akun Anda.",
    "Select a parent category to create a sub-category.": "Pilih kategori induk untuk membuat sub-kategori.",
    "Save Category": "Simpan Kategori",
    "Chart of Accounts": "Bagan Akun (Chart of Accounts)",
    "Organize your income and expense categories (MYOB Accounting Logic).": "Atur kategori pemasukan dan pengeluaran Anda (Logika Akuntansi MYOB).",
    "New Category": "Kategori Baru",
    "Income Accounts": "Akun Pemasukan",
    "No income categories configured.": "Tidak ada kategori pemasukan yang dikonfigurasi.",
    "Recurring": "Berulang",
    "Are you sure?": "Apakah Anda yakin?",
    "Delete": "Hapus",
    "Expense Accounts": "Akun Pengeluaran",
    "No expense categories configured.": "Tidak ada kategori pengeluaran yang dikonfigurasi.",
    "Edit Member": "Edit Anggota",
    "Back to List": "Kembali ke Daftar",
    "Member Name": "Nama Anggota",
    "Community Group": "Grup Komunitas",
    "Select a Group": "Pilih Grup",
    "Exempted": "Dikecualikan",
    "Update Member": "Perbarui Anggota",
    "Add Member": "Tambah Anggota",
    "Save Member": "Simpan Anggota",
    "Members": "Anggota",
    "Members Management": "Manajemen Anggota",
    "Name": "Nama",
    "Group": "Grup",
    "N/A": "T/A",
    "Are you sure you want to delete this member?": "Apakah Anda yakin ingin menghapus anggota ini?",
    "No members found.": "Tidak ada anggota ditemukan.",
    "Contributions Tracking": "Pelacakan Kontribusi",
    "Manage monthly payments for each member. Changes are saved instantly.": "Kelola pembayaran bulanan untuk setiap anggota. Perubahan disimpan secara instan.",
    "Period (YYYY-MM)": "Periode (TTTT-BB)",
    "Load Grid": "Muat Tabel",
    "Payment Status": "Status Pembayaran",
    "Paid": "Lunas",
    "No members found. Please add members first.": "Tidak ada anggota ditemukan. Harap tambahkan anggota terlebih dahulu.",
    "Failed to update status. Please try again.": "Gagal memperbarui status. Silakan coba lagi.",
    "Network error. Could not update status.": "Kesalahan jaringan. Tidak dapat memperbarui status.",
    "Dashboard Analytics": "Analitik Dashboard",
    "Transactions awaiting validation": "Transaksi menunggu validasi",
    "You have": "Anda memiliki",
    "transactions to review in the queue.": "transaksi untuk ditinjau dalam antrean.",
    "Review Queue": "Tinjau Antrean",
    "Total Fund Balance": "Total Saldo Kas",
    "Incomes This Month": "Pemasukan Bulan Ini",
    "Expenses This Month": "Pengeluaran Bulan Ini",
    "This Month: Income vs Expense": "Bulan Ini: Pemasukan vs Pengeluaran",
    "No transactions this month.": "Tidak ada transaksi bulan ini.",
    "6-Month Cash Flow Trend": "Tren Arus Kas 6 Bulan",
    "6-Month Financial Projection": "Proyeksi Keuangan 6 Bulan",
    "Calculated MRR (Monthly Recurring Revenue):": "Perhitungan MRR (Pendapatan Berulang Bulanan):",
    "Projections are calculated dynamically using the 6-month average of categories marked as \"Recurring\", minus any planned activity budgets.": "Proyeksi dihitung secara dinamis menggunakan rata-rata 6 bulan dari kategori yang ditandai sebagai \"Berulang\", dikurangi anggaran kegiatan yang direncanakan.",
    "Latest Transactions": "Transaksi Terbaru",
    "View All": "Lihat Semua",
    "No recent transactions found.": "Tidak ada transaksi terbaru ditemukan.",
    "Upcoming Activities": "Kegiatan Mendatang",
    "No upcoming events planned.": "Tidak ada acara yang direncanakan.",
    "Budget": "Anggaran",
    "Projected Balance": "Saldo Proyeksi",
    "Edit Fund": "Edit Kas",
    "Back to Funds": "Kembali ke Kas",
    "Update the details of this community fund. The balance cannot be changed manually.": "Perbarui detail kas komunitas ini. Saldo tidak dapat diubah secara manual.",
    "Current Balance": "Saldo Saat Ini",
    "Fund Name": "Nama Kas",
    "Associated Group (Optional)": "Grup Terkait (Opsional)",
    "No Group / General Fund": "Tanpa Grup / Kas Umum",
    "Associated Activity (Optional)": "Kegiatan Terkait (Opsional)",
    "No Specific Activity": "Tidak Ada Kegiatan Spesifik",
    "Update Fund": "Perbarui Kas",
    "Create Fund": "Buat Kas",
    "Create New Fund": "Buat Kas Baru",
    "Create a new community fund. The initial balance will always be set to Rp 0.": "Buat kas komunitas baru. Saldo awal akan selalu ditetapkan sebesar Rp 0.",
    "e.g., Kas Umum, Kas Pembangunan": "misal, Kas Umum, Kas Pembangunan",
    "Describe the purpose of this fund (optional)": "Jelaskan tujuan kas ini (opsional)",
    "Save Fund": "Simpan Kas",
    "Funds Management": "Manajemen Kas",
    "Manage community funds and view their current balances.": "Kelola kas komunitas dan lihat saldo saat ini.",
    "New Fund": "Kas Baru",
    "Are you sure you want to delete this fund? This action cannot be undone.": "Apakah Anda yakin ingin menghapus kas ini? Tindakan ini tidak dapat dibatalkan.",
    "No Funds Found": "Tidak Ada Kas Ditemukan",
    "You have not created any funds yet. Create your first fund to start tracking financial transactions.": "Anda belum membuat kas. Buat kas pertama Anda untuk mulai melacak transaksi keuangan.",
    "Create Your First Fund": "Buat Kas Pertama Anda",
    "Dashboard": "Dashboard",
    "New Transaction": "Transaksi Baru",
    "Reports (LPJ)": "Laporan (LPJ)",
    "Logout": "Keluar",
    "Back": "Kembali",
    "Public Transparency": "Transparansi Publik",
    "Generated automatically for public transparency.": "Dihasilkan secara otomatis untuk transparansi publik.",
    "pagination.previous": "Sebelumnya",
    "pagination.next": "Selanjutnya",
    "Pagination Navigation": "Navigasi Halaman",
    "Showing": "Menampilkan",
    "to": "hingga",
    "of": "dari",
    "results": "hasil",
    "Service Unavailable": "Layanan Tidak Tersedia",
    "Unauthorized": "Tidak Sah",
    "Too Many Requests": "Terlalu Banyak Permintaan",
    "Forbidden": "Terlarang",
    "Payment Required": "Pembayaran Diperlukan",
    "Page Expired": "Halaman Kedaluwarsa",
    "Not Found": "Tidak Ditemukan",
    "Server Error": "Kesalahan Server",
    "All rights reserved.": "Hak cipta dilindungi undang-undang.",
    "transactions to review.": "transaksi untuk ditinjau.",
    "Latest 5 Transactions": "5 Transaksi Terakhir",
    "Upcoming Events & Activities": "Acara & Kegiatan Mendatang",
    "Planning": "Perencanaan",
    "Status:": "Status:",
    "Until": "Sampai"
}


# Combine existing with new, prioritizing existing to maintain user overrides if any, but adding all missing ones.
# Actually, the requirement says "everything must be translated". Let's update with our mapping.
for key in keys:
    if key not in fr_existing or fr_existing[key] == key:
        fr_existing[key] = fr_new.get(key, key)
    
    if key not in id_existing or id_existing[key] == key:
        id_existing[key] = id_new.get(key, key)

    # For existing ones, let's just make sure they are updated if we have a better translation in our dict
    if key in fr_new:
        fr_existing[key] = fr_new[key]
    if key in id_new:
        id_existing[key] = id_new[key]

# English is exactly the keys
en_out = {k: k for k in keys}

# Write out the files
with open('lang/en.json', 'w') as f:
    json.dump(en_out, f, indent=4, ensure_ascii=False)

with open('lang/fr.json', 'w') as f:
    json.dump(fr_existing, f, indent=4, ensure_ascii=False)

with open('lang/id.json', 'w') as f:
    json.dump(id_existing, f, indent=4, ensure_ascii=False)

print("Done generating language files.")
